import org.apache.tools.ant.DirectoryScanner

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenLocal()
        mavenCentral()
        maven {
            url("https://jitpack.io")
            content {
                includeGroup("com.github.LSPosed.AutoResConfig")
                includeGroup("com.github.LSPosed.MaterialThemeBuilder")
            }
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "dev.rikka.tools.autoresconfig") {
                useModule("com.github.LSPosed.AutoResConfig:gradle-plugin:${requested.version}")
            }
            if (requested.id.id == "dev.rikka.tools.materialthemebuilder") {
                useModule("com.github.LSPosed.MaterialThemeBuilder:gradle-plugin:${requested.version}")
            }
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        maven {
            url("https://jitpack.io")
            content {
                includeGroup("com.github.topjohnwu.libsu")
            }
        }
    }
}

DirectoryScanner.removeDefaultExclude("**/.gitattributes")

include ':server', ':starter', ':shell'
include ':manager'
include ':common'

def root = "api"

def propFile = file('local.properties')
def props = new Properties()

if (propFile.canRead()) {
    props.load(new FileInputStream(propFile))

    if (props != null) {
        if (props["api.useLocal"] == "true") {
            root = props["api.dir"]
        }
    }
}

include ':aidl'
project(':aidl').projectDir = file("$root${File.separator}aidl")

include ':rish'
project(':rish').projectDir = file("$root${File.separator}rish")

include ':shared'
project(':shared').projectDir = file("$root${File.separator}shared")

include ':api'
project(':api').projectDir = file("$root${File.separator}api")

include ':provider'
project(':provider').projectDir = file("$root${File.separator}provider")

include ':server-shared'
project(':server-shared').projectDir = file("$root${File.separator}server-shared")
